import { IndianRupee } from 'lucide-react'

interface UdhaariPaymentReceiptProps {
    payment: {
        id: string
        customer_name: string
        amount_paid: number
        payment_mode: string
        old_due: number
        new_due: number
        created_at: string
    }
    shopInfo: any
}

export default function UdhaariPaymentReceipt({ payment, shopInfo }: UdhaariPaymentReceiptProps) {
    if (!payment || !shopInfo) return null

    const dateStr = new Date(payment.created_at).toLocaleDateString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric'
    })
    const timeStr = new Date(payment.created_at).toLocaleTimeString('en-IN', {
        hour: '2-digit', minute: '2-digit'
    })

    return (
        <div className="w-[80mm] min-h-[50mm] bg-white text-black p-4 font-sans print:w-[80mm] print:p-0 print:m-0 mx-auto text-sm">
            {/* Header */}
            <div className="text-center mb-4 border-b border-black pb-3">
                <h1 className="text-xl font-black uppercase tracking-widest">{shopInfo.shop_name}</h1>
                <p className="text-[10px] uppercase font-bold">{shopInfo.address}</p>
                <p className="text-[10px] uppercase font-bold">Ph: {shopInfo.phone_number}</p>
            </div>

            {/* Receipt Meta */}
            <div className="text-center mb-4">
                <h2 className="text-sm font-black uppercase border border-black inline-block px-3 py-1 rounded">PAYMENT RECEIPT</h2>
                <div className="flex justify-between text-[10px] font-bold mt-2">
                    <span>Date: {dateStr} {timeStr}</span>
                    <span>No: {payment.id}</span>
                </div>
            </div>

            <div className="mb-4">
                <p className="text-xs uppercase font-bold">Received With Thanks From:</p>
                <p className="text-lg font-black">{payment.customer_name}</p>
            </div>

            {/* Payment Details */}
            <div className="border border-black p-3 mb-4 rounded relative">
                <div className="flex justify-between items-center mb-2">
                    <span className="text-xs font-bold uppercase">Amount Paid</span>
                    <span className="text-xl font-black flex items-center"><IndianRupee className="w-4 h-4 mr-1" />{payment.amount_paid.toLocaleString()}</span>
                </div>
                <div className="flex justify-between items-center">
                    <span className="text-xs font-bold uppercase">Mode</span>
                    <span className="text-sm font-black uppercase">{payment.payment_mode}</span>
                </div>
            </div>

            {/* Ledger Status */}
            <div className="border-t border-b border-black py-2 mb-4">
                <div className="flex justify-between text-xs font-bold mb-1">
                    <span>Previous Outstanding</span>
                    <span>Rs.{payment.old_due.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm font-black mt-2">
                    <span>Remaining Balance</span>
                    <span>Rs.{payment.new_due.toLocaleString()}</span>
                </div>
            </div>

            {/* Footer */}
            <div className="text-center mt-6">
                <p className="text-xs font-black uppercase">Thank you!</p>
                <p className="text-[10px] font-bold mt-1">Generated by MyBizz ERP</p>
                <p className="text-[10px] font-bold">winiks.co</p>
            </div>
        </div>
    )
}
